sudo: required
services:
- docker
before_install:
- docker build -t rwoj/docker-react -f Dockerfile.dev .
script:
- docker run rwoj/docker-react npm run test -- --coverage
deploy:
  provider: heroku
  app: docker-react
  api_key:
    secure: TAdHm3xjcoLdcL1l/V3nL5VnvsqEOqAGWltzgPyCBJlV12t6Ac6IuLZkN8N/phVqB1fK0YCDzumtYKXU/6/inEIrRjVWQQt92jszkqP8hfzV3ANiTkG1Jc6FxaJDa7CZVi/10M5qNAJM8A4ifco4wBU0qQmnW/PoL+Svjke40JzPOTo3NjuPT3AprKrB3HPE6thx5gi1u0EKrEHo/wg6WgyCNnqLVI34cSM7ZWvnTjgVUuTJEf9x0V/ZaYAmFElRGz0RnZfJ4cNuT+g+AINL1AL+gYkecdljBRUwSOzrcqFdWjCuUlccVtr+E98THJg1zA6MxIn3dQkzkbJ1+FeK9Qup3ISCVNGCEH4rySMmm33ze3oeFlWNoS/p2j9vJcmCS4AO4kdl5S2700+tiuceDLhJqsRpyVxp1Y5qzXyHbL3r9K5zW454eijP1ym5JDSXYgeWMvu9ko1HEvZFU0Jzyge3NYriEWoR1KgnVNFF9MGXBedzhlWHyYO0zWE5gjYho7TcsvfUJOCg3nz8TXCU3jhj+VTewEvwsMCJJW3FJowmNdA78SPJYDSSZF8A6RMpUo3n7L2ynXZ1IaP0Hs1wHS0XAXOpKnwpMvzTZmBxOb7At1QzhEoGn69cg7TVMKfKO4/C8ofBPP17i1TKaVAp/V5mVJIc5h9FsVyVXSvLWGY=
